#!/bin/bash

# Fullstack Development Team Workflow - Installation Script
# Auto-generated by ./claude v6.4

set -e

echo "🚀 Installing Fullstack Development Team Workflow..."
echo ""

# Verify we're in the project root with extracted files
if [ ! -d ".claude" ]; then
  echo "❌ Error: .claude directory not found"
  echo "   Make sure you extracted the ZIP in your project root"
  exit 1
fi

# Interactive configuration
echo ""
echo "📝 Configuration Options"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check Node.js availability
echo "🔍 Checking dependencies..."
if ! command -v node &> /dev/null; then
  echo "   ⚠️  Node.js not found"
  echo "   💡 Some configuration features require Node.js"
  echo "   💡 Install Node.js: https://nodejs.org/"
  SKIP_JSON_CONFIG=true
else
  NODE_VERSION=$(node --version)
  echo "   ✓ Node.js found: $NODE_VERSION"
  SKIP_JSON_CONFIG=false
fi
echo ""

# 1. Settings.local.json configuration
if [ "$SKIP_JSON_CONFIG" = true ]; then
  echo "1️⃣  Configure .claude/settings.local.json?"
  echo "   ⚠️  Skipped (Node.js required)"
  echo ""
else
  echo "1️⃣  Configure .claude/settings.local.json?"
  echo "   • Add customInstructions from CLAUDE.md"
  echo "   • Auto-approve workflow log writes"
  if [ ! -f ".claude/settings.local.json" ]; then
    echo "   • Create settings.local.json (doesn't exist yet)"
  fi
  echo ""

  PS3="   Select: "
  options=("Yes" "No")
  select opt in "${options[@]}"; do
    case $opt in
      "Yes")
        CONFIGURE_SETTINGS=true
        break
        ;;
      "No")
        CONFIGURE_SETTINGS=false
        break
        ;;
      *)
        echo "   Invalid option. Please select 1 or 2."
        ;;
    esac
  done
  echo ""

  if [ "$CONFIGURE_SETTINGS" = true ]; then
    echo "   ⚙️  Configuring settings.local.json..."

    # Create settings.local.json if it doesn't exist
    if [ ! -f ".claude/settings.local.json" ]; then
      echo '{}' > .claude/settings.local.json
      echo "      ✓ Created settings.local.json"
    fi

    CLAUDE_CONTENT=$(cat .claude/CLAUDE.md)
    node -e "
    const fs = require('fs');
    const settings = JSON.parse(fs.readFileSync('.claude/settings.local.json', 'utf8'));

    // Update customInstructions if empty or null
    const existingInstructions = settings.customInstructions || '';
    if (!existingInstructions || existingInstructions === 'null') {
      settings.customInstructions = \`${CLAUDE_CONTENT}\`;
      console.log('      ✓ customInstructions added');
    } else {
      console.log('      ⊘ customInstructions already exists');
      console.log('      💡 Manually merge if needed: .claude/CLAUDE.md');
    }

    // Add auto-approval for workflow logs
    if (!settings.alwaysApproveTools) {
      settings.alwaysApproveTools = [];
    }

    // Add Bash auto-approval for log writes
    const logPattern = 'Bash(echo*>>*workflow-execution.log:*)';
    if (!settings.alwaysApproveTools.includes(logPattern)) {
      settings.alwaysApproveTools.push(logPattern);
      console.log('      ✓ Auto-approval added for workflow logs');
    }

    fs.writeFileSync('.claude/settings.local.json', JSON.stringify(settings, null, 2));
    " 2>/dev/null || echo "      ⚠️  Node.js not available, skipping settings update"
  else
    echo "   ⊘ Skipped settings.local.json configuration"
  fi
fi
echo ""

# 2. VSCode settings configuration
echo "2️⃣  Configure .vscode/settings.json?"
echo "   • Add claudeCode.additionalArgs: ["--dangerously-skip-permissions"]"
echo "   • Skips permission prompts for tool usage"
echo ""

PS3="   Select: "
options=("Yes" "No")
select opt in "${options[@]}"; do
  case $opt in
    "Yes")
      CONFIGURE_VSCODE=true
      break
      ;;
    "No")
      CONFIGURE_VSCODE=false
      break
      ;;
    *)
      echo "   Invalid option. Please select 1 or 2."
      ;;
  esac
done
echo ""

if [ "$CONFIGURE_VSCODE" = true ]; then
  echo "   🔧 Configuring VSCode settings..."

  if [ ! -d ".vscode" ]; then
    mkdir -p .vscode
  fi

  VSCODE_SETTINGS=".vscode/settings.json"
  if [ -f "$VSCODE_SETTINGS" ]; then
    # Check if setting already exists
    if grep -q "claudeCode.additionalArgs" "$VSCODE_SETTINGS"; then
      echo "      ⊘ VSCode setting already configured"
    else
      # Add setting to existing file (before last closing brace)
      sed -i.bak '$ d' "$VSCODE_SETTINGS"
      if [ -s "$VSCODE_SETTINGS" ] && [ "$(tail -c 2 "$VSCODE_SETTINGS")" != "{" ]; then
        echo "," >> "$VSCODE_SETTINGS"
      fi
      echo "  \"claudeCode.additionalArgs\": [\"--dangerously-skip-permissions\"]" >> "$VSCODE_SETTINGS"
      echo "}" >> "$VSCODE_SETTINGS"
      rm "${VSCODE_SETTINGS}.bak"
      echo "      ✓ VSCode setting added"
    fi
  else
    # Create new settings file
    cat > "$VSCODE_SETTINGS" << 'VSCODE_EOF'
{
  "claudeCode.additionalArgs": ["--dangerously-skip-permissions"]
}
VSCODE_EOF
    echo "      ✓ VSCode settings created"
  fi
else
  echo "   ⊘ Skipped VSCode settings configuration"
fi
echo ""

# 3. Devcontainer configuration
if [ -d "claude.config/devcontainer" ]; then
  echo "3️⃣  Setup devcontainer?"
  echo "   • Docker-based development environment"
  echo "   • Network firewall for security"
  echo "   • Pre-configured for Claude Code"
  echo ""

  PS3="   Select: "
  options=("Yes" "No")
  select opt in "${options[@]}"; do
    case $opt in
      "Yes")
        SETUP_DEVCONTAINER=true
        break
        ;;
      "No")
        SETUP_DEVCONTAINER=false
        break
        ;;
      *)
        echo "   Invalid option. Please select 1 or 2."
        ;;
    esac
  done
  echo ""

  if [ "$SETUP_DEVCONTAINER" = true ]; then
    echo "   🐳 Devcontainer already exists"
    echo "      ✓ claude.config/devcontainer/devcontainer.json"
    echo "      ✓ claude.config/devcontainer/Dockerfile"
    echo "      ✓ claude.config/devcontainer/init-firewall.sh"
    echo ""
    echo "   💡 To use: 'Reopen in Container' in VS Code"
  else
    echo "   ⊘ Skipped devcontainer setup"
  fi
else
  echo "3️⃣  Devcontainer files are available in claude.config/devcontainer/"
  echo "   💡 To use: 'Reopen in Container' in VS Code"
fi
echo ""

# 4. TTS Completion Notification
if [ "$SKIP_JSON_CONFIG" = false ]; then
  echo "4️⃣  Add TTS notification for workflow completion?"
  echo "   • Plays audio notification when workflow completes"
  echo "   • Uses system text-to-speech (say/spd-say/PowerShell)"
  echo ""

  PS3="   Select: "
  options=("Yes" "No")
  select opt in "${options[@]}"; do
    case $opt in
      "Yes")
        ENABLE_TTS=true
        break
        ;;
      "No")
        ENABLE_TTS=false
        break
        ;;
      *)
        echo "   Invalid option. Please select 1 or 2."
        ;;
    esac
  done
  echo ""

  if [ "$ENABLE_TTS" = true ]; then
    echo "   🔊 Configuring TTS completion notification..."

    # Detect OS
    OS_TYPE="unknown"
    if [[ "$OSTYPE" == "darwin"* ]]; then
      OS_TYPE="macos"
      TTS_CMD="say '작업 완료'"
    elif [[ "$OSTYPE" == "msys"* ]] || [[ "$OSTYPE" == "win32"* ]] || [[ "$OSTYPE" == "cygwin"* ]]; then
      OS_TYPE="windows"
      TTS_CMD='powershell -Command "[console]::beep(800,300)"'
    elif command -v spd-say &> /dev/null; then
      OS_TYPE="linux-speechd"
      TTS_CMD="spd-say '작업 완료'"
    elif command -v espeak &> /dev/null; then
      OS_TYPE="linux-espeak"
      TTS_CMD="espeak '작업 완료'"
    else
      OS_TYPE="unknown"
      TTS_CMD="echo '🔔 작업 완료!'"
    fi

    echo "      Detected OS: $OS_TYPE"

    # For Windows, ask for confirmation
    if [ "$OS_TYPE" = "windows" ]; then
      echo ""
      echo "      ⚠️  Windows detected"
      echo "      PowerShell TTS will be used (requires PowerShell 5.0+)"
      echo "      Continue? (Yes/No)"
      echo ""

      PS3="      Select: "
      options=("Yes" "No")
      select opt in "${options[@]}"; do
        case $opt in
          "Yes")
            break
            ;;
          "No")
            ENABLE_TTS=false
            echo "      ⊘ Skipped TTS setup"
            break
            ;;
          *)
            echo "      Invalid option. Please select 1 or 2."
            ;;
        esac
      done
      echo ""
    fi

    if [ "$ENABLE_TTS" = true ]; then
      # Add agent-done-hook to settings.local.json
      node -e "
        const fs = require('fs');
        const settings = JSON.parse(fs.readFileSync('.claude/settings.local.json', 'utf8'));

        if (!settings.hooks) {
          settings.hooks = {};
        }

        const ttsCommand = \`${TTS_CMD}\`;
        const hookContent = \`
📢 워크플로우 작업이 완료되었습니다!

다음 명령어를 실행하여 알림을 재생하세요:

\\`\\`\\`bash
${ttsCommand}
\\`\\`\\`

또는 아래 명령어를 복사하세요:

BASH_TO_RUN: ${ttsCommand}
\`.trim();

        // Check if agent-done-hook exists
        const existingHook = settings.hooks['agent-done-hook'] || '';

        if (existingHook && existingHook.trim() !== '') {
          console.log('      ⚠️  Existing agent-done-hook found');
          console.log('      💡 TTS command will be appended');
          settings.hooks['agent-done-hook'] = existingHook + '\n\n---\n\n' + hookContent;
        } else {
          settings.hooks['agent-done-hook'] = hookContent;
        }

        fs.writeFileSync('.claude/settings.local.json', JSON.stringify(settings, null, 2));
        console.log('      ✓ TTS notification hook added');
        console.log('      ✓ TTS command: ${ttsCommand}');
      " 2>/dev/null || echo "      ⚠️  Failed to configure TTS hook"
    fi
  else
    echo "   ⊘ Skipped TTS notification setup"
  fi
  echo ""
else
  echo "4️⃣  TTS notification setup"
  echo "   ⚠️  Skipped (Node.js required)"
  echo ""
fi

echo ""
echo "✅ Installation complete!"
echo ""
echo "📦 Installed components:"
echo "   ✓ .claude/commands/fullstack-development-team-workflow.md"
echo "   ✓ .claude/agents/*.md"
echo "   ✓ .claude/CLAUDE.md"
echo "   ✓ claude.config/devcontainer/ (Docker + firewall)"
echo "   ✓ claude.config/fullstack-development-team-workflow/docs/ (documentation)"
echo ""
echo "📖 Next steps:"
echo "   1. Restart Claude Code (important!)"
echo "   2. Run: /fullstack-development-team-workflow <your task>"
echo ""
echo "💡 Tips:"
echo "   - View logs: cat claude.config/fullstack-development-team-workflow/docs/workflow-execution.log"
echo "   - Read docs: cat README.md (or QUICKSTART.md)"
echo "   - Use devcontainer: Reopen in Container (VS Code)"
echo ""
echo "🎉 Happy coding with multi-agent workflows!"
