#!/bin/bash

# Workflow Structure Validation Script
# Generated by ./claude

set -e

echo "🔍 Validating workflow structure..."
echo ""

ERRORS=0

# Check .claude directory
if [ ! -d ".claude" ]; then
  echo "❌ .claude/ directory not found"
  ERRORS=$((ERRORS + 1))
else
  echo "✅ .claude/ directory exists"
fi

# Check commands directory
if [ ! -d ".claude/commands" ]; then
  echo "❌ .claude/commands/ directory not found"
  ERRORS=$((ERRORS + 1))
else
  echo "✅ .claude/commands/ directory exists"
fi

# Check command file
if [ ! -f ".claude/commands/fullstack-development-team-workflow.md" ]; then
  echo "❌ Command file .claude/commands/fullstack-development-team-workflow.md not found"
  ERRORS=$((ERRORS + 1))
else
  echo "✅ Command file exists"
fi

# Check agents directory
if [ ! -d ".claude/agents" ]; then
  echo "❌ .claude/agents/ directory not found"
  ERRORS=$((ERRORS + 1))
else
  echo "✅ .claude/agents/ directory exists"

  # Count agent files
  AGENT_COUNT=$(ls -1 .claude/agents/*.md 2>/dev/null | wc -l)
  echo "   Found $AGENT_COUNT agent files (expected 6)"

  if [ "$AGENT_COUNT" -ne 6 ]; then
    echo "⚠️  Agent count mismatch!"
  fi
fi

# Check CLAUDE.md
if [ ! -f ".claude/CLAUDE.md" ]; then
  echo "⚠️  .claude/CLAUDE.md not found (recommended)"
else
  echo "✅ .claude/CLAUDE.md exists"
fi

# Check documentation
if [ ! -d "claude.config/fullstack-development-team-workflow/docs" ]; then
  echo "⚠️  claude.config/fullstack-development-team-workflow/docs/ directory not found (recommended)"
else
  echo "✅ claude.config/fullstack-development-team-workflow/docs/ directory exists"
fi

echo ""
if [ $ERRORS -eq 0 ]; then
  echo "✅ Validation passed! Structure is correct."
  exit 0
else
  echo "❌ Validation failed with $ERRORS errors."
  exit 1
fi
